# Use root/example as user/password credentials
version: '3.1'

volumes:
  local_pg_data: {}

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - local_pg_data:/var/lib/postgresql/jvp-sh:Z
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DATABASE}

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: jvp-sh-go_mailhog
    ports:
      - '8025:8025'
      - '1025:1025'
